language: php

cache:
  directories:
    - $HOME/.composer/cache/files/

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - coverage=false
    - lint=false
    - phpstan=false
    - setup=basic

sudo: false

before_install:
  - if [[ $coverage = 'false' ]] ; then phpenv config-rm xdebug.ini || true ; fi

install:
  - if [[ $lint = 'false' ]] ; then travis_retry composer remove friendsofphp/php-cs-fixer --no-update --dev ; fi
  - if [[ $phpstan = 'true' ]] ; then travis_retry composer require phpstan/phpstan --no-update --dev ; fi
  - if [[ $setup = 'basic' ]] ; then travis_retry composer install --prefer-dist --no-interaction --no-suggest ; fi
  - if [[ $setup = 'stable' ]] ; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable ; fi
  - |
    if [[ $setup = 'lowest' ]] ; then
        composer require sebastian/comparator:">=1.2.4" --no-update --dev
        travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest
    fi

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
  - if [[ $phpstan = 'true' ]] ; then vendor/bin/phpstan analyse --configuration phpstan.neon --level 7 src tests ; fi

after_success:
  - if [[ $coverage = 'true' ]] ; then bash <(curl -s https://codecov.io/bash) ; fi

matrix:
  include:
    - php: 5.4
      env: setup=lowest
    - php: 5.4
      env: setup=stable
    - php: 5.5
      env: setup=lowest
    - php: 5.5
      env: setup=stable
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env:
        - lint=true
        - phpstan=true
        - setup=stable
    - php: 7.1
      env:
        - lint=true
        - phpstan=true
        - setup=lowest
    - php: 7.1
      env:
        - lint=true
        - coverage=true
        - phpstan=true
        - setup=stable
    - php: 7.2
      env:
        - lint=true
        - phpstan=true
        - setup=lowest
    - php: 7.2
      env:
        - coverage=true
        - lint=true
        - phpstan=true
        - setup=stable
  allow_failures:
    - php:
        - nightly
  fast_finish: true
